apiVersion: v1
kind: Service
metadata:
  name: infra-demo-service
  labels:
    app: infra-demo
spec:
  type: ClusterIP
  selector:
    app: infra-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
